version: '3.8'
services:
  homeassistant:
    container_name: ha-dev-test
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      # Fresh HA config directory for isolated testing
      - ./testing_env/config:/config
      # Direct mapping of addon code for instant development
      - ./addons:/usr/share/hassio/addons
      # Map data directory for addon persistence testing
      - ./testing_env/data:/data
    environment:
      - TZ=America/New_York
    privileged: false
    network_mode: bridge
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8123 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Local MQTT broker for testing (using different ports to avoid conflicts)
  mosquitto:
    container_name: mqtt-dev-test
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1883"  # Use port 1884 for testing to avoid conflict with real broker
      - "9002:9001"  # Use port 9002 for websockets to avoid conflicts
    volumes:
      - ./testing_env/mosquitto/config:/mosquitto/config
      - ./testing_env/mosquitto/data:/mosquitto/data
      - ./testing_env/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    
networks:
  default:
    name: aicleaner-test-network