# Home Assistant Configuration for AICleaner v3 Testing
# Minimal configuration for fast startup and MQTT integration testing

# Core configuration
homeassistant:
  name: AICleaner Test Environment
  latitude: 40.7128
  longitude: -74.0060
  elevation: 0
  unit_system: metric
  time_zone: America/New_York
  
# Disable default config for faster startup and minimal resource usage
# default_config:

# Essential components for testing
api:
http:
  server_port: 8123
  
# Frontend for debugging (optional)
frontend:

# MQTT integration pointing to our test broker
mqtt:
  broker: mosquitto-test
  port: 1883
  # Anonymous connection for testing environment
  # username: aicleaner  
  # password: test_password
  discovery: true
  discovery_prefix: homeassistant
  
# Logger configuration for debugging
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.api: debug

# Enable automation for testing purposes
automation: !include automations.yaml

# Enable script functionality
script: !include scripts.yaml

# Enable scenes
scene: !include scenes.yaml

# Text to speech (minimal)
tts:
  - platform: google_translate