# AICleaner Home Assistant Service Descriptions
# This file provides UI descriptions for services registered by the addon

run_analysis:
  name: "Run Zone Analysis"
  description: "Manually trigger AI analysis for a specific zone"
  fields:
    zone_name:
      description: "Name of the zone to analyze"
      example: "Rowan's Room"
      required: true
      selector:
        text:

refresh_zones:
  name: "Refresh All Zones"
  description: "Refresh configuration and status for all zones"

toggle_zone:
  name: "Toggle Zone Monitoring"
  description: "Enable or disable monitoring for a specific zone"
  fields:
    zone_name:
      description: "Name of the zone to toggle"
      example: "Rowan's Room"
      required: true
      selector:
        text:
    enabled:
      description: "Enable or disable the zone"
      required: true
      selector:
        boolean:

clear_zone_tasks:
  name: "Clear Zone Tasks"
  description: "Clear all tasks for a specific zone"
  fields:
    zone_name:
      description: "Name of the zone to clear tasks for"
      example: "Rowan's Room"
      required: true
      selector:
        text:

restart_addon:
  name: "Restart AICleaner"
  description: "Restart the AICleaner addon"

run_health_check:
  name: "Run Health Check"
  description: "Run a comprehensive 30-second system health check and update health sensors"
  fields:
    duration:
      description: "Duration of the health check in seconds"
      example: 30
      default: 30
      required: false
      selector:
        number:
          min: 10
          max: 120
          step: 5
          unit_of_measurement: "seconds"

apply_performance_profile:
  name: "Apply Performance Profile"
  description: "Change the active performance profile (requires restart to take effect)"
  fields:
    profile:
      description: "Performance profile to apply"
      example: "balanced"
      required: true
      selector:
        select:
          options:
            - "auto"
            - "resource_efficient"
            - "balanced"
            - "maximum_performance"
