# AICleaner v3 Multi-Tier Configuration
name: "AICleaner v3 Multi-Tier"
version: "3.0.0"
description: "AI-powered Home Assistant addon with multi-tier architecture"

# Multi-Tier Architecture Configuration
multi_tier:
  enabled: true
  default_tier: "hybrid"  # hybrid, local, cloud
  
  # Tier 1: Privacy-Preserving Hybrid
  hybrid:
    enabled: true
    privacy_pipeline: true
    cloud_fallback: true
    target_response_time: 15  # seconds
  
  # Tier 2: Full Local Processing
  local:
    enabled: true
    amd_optimization: true
    model_preference: "llava:7b"
    target_response_time: 120  # seconds
  
  # Tier 3: Pure Cloud
  cloud:
    enabled: true
    providers: ["openai", "anthropic", "google"]
    target_response_time: 10  # seconds

# Privacy Pipeline Configuration
privacy:
  enabled: true
  default_level: "balanced"  # paranoid, balanced, speed
  preprocessing_timeout: 5   # seconds
  
  levels:
    paranoid:
      face_detection: true
      text_sanitization: true
      object_anonymization: true
      pii_removal: true
    balanced:
      face_detection: true
      text_sanitization: true
      object_anonymization: false
      pii_removal: true
    speed:
      face_detection: false
      text_sanitization: true
      object_anonymization: false
      pii_removal: false

# AMD Hardware Optimization
amd_optimization:
  enabled: true
  cpu: "8845hs"
  igpu: "780m"
  memory: "64gb"
  
  models:
    llava_7b:
      enabled: true
      gpu_layers: 20
      context_length: 4096
      quantization: "Q4_K_M"
    llava_13b:
      enabled: true
      gpu_layers: 26
      context_length: 4096
      quantization: "Q4_K_M"

# Cloud Provider Configuration (Simplified)
providers:
  openai:
    enabled: true
    priority: 1
    model: "gpt-4-vision-preview"
    timeout: 10
    
  anthropic:
    enabled: true
    priority: 2
    model: "claude-3-5-sonnet-20241022"
    timeout: 10
    
  google:
    enabled: true
    priority: 3
    model: "gemini-1.5-flash"
    timeout: 8
    
  llamacpp_amd:
    enabled: true
    priority: 4
    model: "llava:7b"
    timeout: 120

# Home Assistant Integration
home_assistant:
  enabled: true
  api_url: "http://supervisor/core/api"
  zones:
    - name: "Living Room"
      camera: "camera.living_room"
      todo_list: "todo.living_room_tasks"
    - name: "Kitchen"  
      camera: "camera.kitchen"
      todo_list: "todo.kitchen_tasks"

# Logging Configuration
logging:
  level: "INFO"
  file: "/data/logs/aicleaner.log"
  max_size: "10MB"
  backup_count: 5
