# Home Assistant Add-on Build Configuration
# Multi-architecture build support for AICleaner v3

# Build arguments passed to Dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.19

# Build arguments
args:
  BUILD_VERSION: "1.0.0"
  BUILD_DATE: "2025-01-19T00:00:00Z"
  BUILD_REF: "main"

# Supported architectures
codenotary:
  signer: "notary@aicleaner.dev"
  base_image: "ghcr.io/home-assistant/{arch}-base-python:3.12-alpine3.19"

# Image labels
labels:
  maintainer: "AICleaner Team <support@aicleaner.dev>"
  org.opencontainers.image.title: "AICleaner v3"
  org.opencontainers.image.description: "Advanced AI-powered Home Assistant automation"
  org.opencontainers.image.source: "https://github.com/drewcifer/aicleaner_v3"
  org.opencontainers.image.licenses: "MIT"