name: "AICleaner v3"
version: "3.0.0"
slug: "aicleaner_v3"
description: "Advanced AI-powered Home Assistant automation with intelligent device management"
url: "https://github.com/yourusername/aicleaner_v3"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
privileged:
  - SYS_ADMIN
map:
  - config:rw
  - ssl:rw
  - addons_config:rw
  - share:rw
  - media:rw
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "AICleaner Web Interface"
options:
  log_level: info
  ai_providers:
    - provider: openai
      enabled: true
    - provider: gemini
      enabled: true
  zones:
    - name: "Living Room"
      enabled: true
      devices: []
  security:
    enabled: true
    encryption: true
    audit_logging: true
  performance:
    auto_optimization: true
    resource_monitoring: true
    caching: true
  privacy:
    enabled: true
    level: "balanced"
    models:
      face_detection:
        speed: "models/yunet.onnx"
        balanced: "models/retinaface.onnx"
        paranoid: "models/scrfd.onnx"
      object_detection:
        general: "models/yolov8m.onnx"
        license_plates: "models/yolov8_license_plates.onnx"
      text_detection: "models/paddle_ocr.onnx"
    redaction:
      face_mode: "blur"
      license_plate_mode: "black_box"
      pii_text_mode: "black_box"
    performance:
      max_image_size: [1920, 1080]
      parallel_processing: true
      model_caching: true
      async_processing: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  ai_providers:
    - provider: str
      enabled: bool
      api_key: password?
      model: str?
      max_tokens: int?
  zones:
    - name: str
      enabled: bool
      devices: [str]
      automation_rules: [str]?
  security:
    enabled: bool
    encryption: bool
    audit_logging: bool
    ssl_certificate: str?
    ssl_key: str?
  performance:
    auto_optimization: bool
    resource_monitoring: bool
    caching: bool
    max_memory_mb: int?
    max_cpu_percent: int?
  privacy:
    enabled: bool
    level: list(speed|balanced|paranoid)
    models:
      face_detection:
        speed: str
        balanced: str
        paranoid: str
      object_detection:
        general: str
        license_plates: str
      text_detection: str
    redaction:
      face_mode: list(blur|pixelate|black_box)
      license_plate_mode: list(blur|pixelate|black_box)
      pii_text_mode: list(blur|pixelate|black_box)
    performance:
      max_image_size: [int]
      parallel_processing: bool
      model_caching: bool
      async_processing: bool
image: "ghcr.io/yourusername/aicleaner_v3"
services:
  - mqtt:server
  - mysql:want
startup: application
boot: auto
hassio_api: true
hassio_role: admin
homeassistant_api: true
host_network: false
auto_uart: false
devices:
  - /dev/ttyUSB0
  - /dev/ttyACM0
udev: true
apparmor: true
