analyze_camera:
  name: Analyze Camera
  description: Analyze a camera image using AI
  fields:
    entity_id:
      name: Camera Entity
      description: Camera entity to analyze
      required: true
      selector:
        entity:
          domain: camera
    prompt:
      name: Analysis Prompt
      description: What to analyze in the image
      required: false
      default: "Analyze this camera image"
      selector:
        text:
    provider:
      name: AI Provider
      description: Specific AI provider to use (optional)
      required: false
      selector:
        select:
          options:
            - openai
            - anthropic
            - gemini
            - ollama
    save_result:
      name: Save Result
      description: Save analysis result to a text sensor
      required: false
      default: true
      selector:
        boolean:

generate_text:
  name: Generate Text
  description: Generate text using AI for automation responses
  fields:
    prompt:
      name: Prompt
      description: Text prompt for AI generation
      required: true
      selector:
        text:
          multiline: true
    provider:
      name: AI Provider
      description: Specific AI provider to use (optional)
      required: false
      selector:
        select:
          options:
            - openai
            - anthropic
            - gemini
            - ollama
    temperature:
      name: Temperature
      description: Controls randomness (0.0-2.0)
      required: false
      default: 0.7
      selector:
        number:
          min: 0.0
          max: 2.0
          step: 0.1
    max_tokens:
      name: Max Tokens
      description: Maximum tokens to generate
      required: false
      default: 1000
      selector:
        number:
          min: 1
          max: 8192

check_provider_status:
  name: Check Provider Status
  description: Check if specific AI provider is available
  fields:
    provider:
      name: AI Provider
      description: Provider name to check
      required: true
      selector:
        select:
          options:
            - openai
            - anthropic
            - gemini
            - ollama

switch_provider:
  name: Switch Provider
  description: Switch active AI provider for subsequent requests
  fields:
    provider:
      name: AI Provider
      description: Provider to switch to
      required: true
      selector:
        select:
          options:
            - openai
            - anthropic
            - gemini
            - ollama