name: "AICleaner V3"
version: "1.0.0"
slug: "aicleaner_v3"
description: "AI-powered Home Assistant automation addon for personal, hobbyist use. Provides intelligent device management, MQTT discovery, and AI-enhanced automation capabilities."
url: "https://github.com/drewcifer/aicleaner_v3"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: false
privileged: false
map:
  - data:rw
  - config:rw
  - ssl:ro
ports: {}
options:
  log_level: "info"
  primary_api_key: ""
  backup_api_keys: []
  mqtt_discovery_prefix: "homeassistant"
  device_id: "aicleaner_v3"
  # Advanced configuration
  testing_mode: false
  performance_monitoring: true
  ai_provider_timeout: 30
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  primary_api_key: "password"
  backup_api_keys:
    - "password"
  mqtt_discovery_prefix: "str"
  device_id: "str"
  testing_mode: "bool?"
  performance_monitoring: "bool?"
  ai_provider_timeout: "int(5,300)?"
services:
  - "mqtt:want"
image: "ghcr.io/drewcifer/aicleaner_v3/{arch}"