build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"

args:
  PYTHON_VERSION: "3.12"

labels:
  io.hass.name: "AICleaner V3"
  io.hass.description: "AI-powered cleaning task management with intelligent zone monitoring and automatic dashboard integration"
  io.hass.arch: "{arch}"
  io.hass.type: "addon"
  io.hass.version: "{version}"
  maintainer: "sporebattyl"
  
# codenotary configuration removed for community addon compatibility