name: "AICleaner V3"
version: "1.0.1"
slug: "aicleaner_v3"
description: "AI-powered cleaning task management with intelligent zone monitoring and automatic dashboard integration"
url: "https://github.com/drewcifer/aicleaner_v3/tree/main/addons/aicleaner_v3"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: false
privileged: []
ingress: true
ingress_port: 8080
panel_icon: "mdi:robot-vacuum"
panel_title: "AI Cleaner v3"
map:
  - data:rw
  - config:rw
  - ssl:ro
ports: {}
options:
  # Essential settings only - MQTT and Dashboard are auto-configured
  log_level: "info"
  device_id: "aicleaner_v3"
  
  # AI Provider API Keys (optional - can use local Ollama)
  primary_api_key: ""
  backup_api_keys: []
  
  # MQTT Discovery (automatically configured via Home Assistant services)
  mqtt_discovery_prefix: "homeassistant"
  
  # Advanced options (optional)
  debug_mode: false
  auto_dashboard: true

schema:
  # Essential settings
  log_level: "list(debug|info|warning|error)"
  device_id: "str"
  
  # AI Provider API Keys (optional)
  primary_api_key: "password?"
  backup_api_keys: ["password?"]
  
  # MQTT Discovery (auto-configured)
  mqtt_discovery_prefix: "str"
  
  # Advanced options
  debug_mode: "bool"
  auto_dashboard: "bool"
services:
  - "mqtt:want"
image: "ghcr.io/drewcifer/aicleaner_v3/{arch}"