name: "AICleaner V3"
version: "1.1.4"
slug: "aicleaner_v3"
description: "AI-powered cleaning task management with intelligent zone monitoring and automatic dashboard integration"
url: "https://github.com/sporebattyl/aicleaner_v3/tree/main/aicleaner_v3"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: manager
homeassistant_api: true
auth_api: true
host_network: false
privileged: []
ingress: true
ingress_port: 8080
panel_icon: "mdi:broom"
panel_title: "AI Cleaner v3"
map:
  - data:rw
  - config:rw
  - ssl:ro
ports: {}
options:
  # Essential settings only - MQTT and Dashboard are auto-configured
  log_level: "info"
  device_id: "aicleaner_v3"
  
  # AI Provider API Keys (optional - can use local Ollama)
  primary_api_key: ""
  backup_api_keys: []
  
  # MQTT Discovery (automatically configured via Home Assistant services)
  mqtt_discovery_prefix: "homeassistant"
  
  # Entity Selections (Basic Mode)
  default_camera: ""
  default_todo_list: ""
  
  # Zone Configuration (Advanced Mode - Optional)
  enable_zones: false
  zones: []
  
  # Advanced options (optional)
  debug_mode: false
  auto_dashboard: true

schema:
  # Essential settings
  log_level: "list(debug|info|warning|error)"
  device_id: "str"
  
  # AI Provider API Keys (optional)
  primary_api_key: "str?"
  backup_api_keys: "list(str)?"
  
  # MQTT Discovery (auto-configured)
  mqtt_discovery_prefix: "str"
  
  # Entity Selections (Basic Mode) - Manual entity ID entry
  default_camera: "str?"
  default_todo_list: "str?"
  
  # Zone Configuration (Advanced Mode)
  enable_zones: "bool"
  zones: "list(dict)"
  
  # Advanced options
  debug_mode: "bool"
  auto_dashboard: "bool"
services:
  - "mqtt:want"
image: "ghcr.io/sporebattyl/aicleaner_v3/{arch}"