name: "AICleaner V3"
version: "1.0.0"
slug: "aicleaner_v3"
description: "Intelligently cleans and processes data using AI."
url: "https://github.com/drewcifer/aicleaner_v3/tree/main/addons/aicleaner_v3"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: false
privileged: false
map:
  - data:rw
  - config:rw
  - ssl:ro
ports: {}
options:
  log_level: "info"
  primary_api_key: ""
  backup_api_keys: []
  mqtt_discovery_prefix: "homeassistant"
  device_id: "aicleaner_v3"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  primary_api_key: "password"
  backup_api_keys:
    - "password"
  mqtt_discovery_prefix: "str"
  device_id: "str"
services:
  - "mqtt:want"
image: "ghcr.io/drewcifer/aicleaner_v3/{arch}"