name: Build and Publish Addon

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push addon
        uses: home-assistant/builder@master
        with:
          args: |
            --target ./addons/aicleaner_v3 \
            --all \
            --docker-hub ${{ env.REGISTRY }}/${{ github.repository_owner }}/aicleaner_v3 \
            --docker-user ${{ github.repository_owner }} \
            --docker-password ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_BUILDKIT: 1