name: Build and Publish Addon

on:
  push:
    branches: [main]
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --target ./aicleaner_v3 \
            --amd64 \
            --docker-hub ${{ env.REGISTRY }} \
            --image aicleaner_v3