name: Build Home Assistant Addon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  info:
    runs-on: ubuntu-latest
    name: Get addon information
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      name: ${{ steps.info.outputs.name }}
      slug: ${{ steps.info.outputs.slug }}
      version: ${{ steps.info.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get addon info
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./addons/aicleaner_v3

  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} addon
    needs: info
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        arch: ${{ fromJson(needs.info.outputs.architectures) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build addon
        uses: home-assistant/builder@master
        with:
          args: |
            --target ./addons/aicleaner_v3 \
            --${{ matrix.arch }}

  publish:
    runs-on: ubuntu-latest
    name: Publish addon
    needs: [info, build]
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish addon
        uses: home-assistant/builder@master
        with:
          args: |
            --target ./addons/aicleaner_v3 \
            --all \
            --with-codenotary